sportngin/okcomputer

lib/ok_computer/built_in_checks/sidekiq_latency_check.rb, lib/okcomputer.rb, spec/ok_computer/built_in_checks/sidekiq_latency_check_spec.rb
Hi, thanks for building OkComputer!
I needed a Sidekiq queue check in my application. Sidekiq's recommended way to monitor a queue is to check for latency (the age of the oldest job).
This was totally based off of the backed-up Resque queue check.
I figured since Sidekiq is pretty widely used, it would be nice to include this as a built-in check.
=> Add built-in Sidekiq latency check

lib/ok_computer/built_in_checks/app_version_check.rb, lib/okcomputer.rb, spec/ok_computer/built_in_checks/app_version_check_spec.rb, spec/spec_helper.rb, spec/support/helpers.rb
Closes https://github.com/sportngin/okcomputer/issues/48
* Checks for `ENV["SHA"]` and uses that value
* Otherwise, checks for the Capistrano `REVISION` file in the app root
* In absence of any of these, the check fails
=> Add check to determine app version

lib/ok_computer/built_in_checks/mongoid_check.rb, spec/ok_computer/built_in_checks/mongoid_check_spec.rb, spec/ok_computer/built_in_checks/mongoid_replica_set_check_spec.rb
This makes `MongoidCheck` consistent with `MongoidReplicaSetCheck` in supporting different Mongoid sessions.
I also added specs for session support.
My motivation for this was because some environments are set up with a replica set, and some are not. But I still needed to check the same session.
=> Support specifying a session for MongoidCheck

lib/ok_computer/built_in_checks/elasticsearch_check.rb, lib/ok_computer/built_in_checks/http_check.rb, lib/ok_computer/built_in_checks/solr_check.rb, lib/okcomputer.rb, spec/ok_computer/built_in_checks/elasticsearch_check_spec.rb, spec/ok_computer/built_in_checks/http_check_spec.rb, spec/ok_computer/built_in_checks/solr_check_spec.rb
I needed to do a health check for Solr. In the process, it made sense to extract a generic `HttpCheck` that can be used to check any HTTP endpoint. The existing `ElasticsearchCheck` has been refactored to inherit from `HttpCheck`. The new `SolrCheck` also inherits from `HttpCheck`.
Thinking ahead, I think it makes sense to keep "core" generic checks like `SizeThresholdCheck` and `HttpCheck` in the `okcomputer` gem, and move most of the technology-specific checks to `okcomputer-contrib`.
=> HTTP check + Solr check

lib/ok_computer/built_in_checks/mongoid_check.rb
Mongoid.sessions is deprecated and Mongoid::Sessions is no longer defined.
=> update mongoid_check to be compatible with mongoid 5

lib/ok_computer/built_in_checks/mongoid_check.rb, lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb, spec/ok_computer/built_in_checks/mongoid_check_spec.rb, spec/ok_computer/built_in_checks/mongoid_replica_set_check_spec.rb
If you do not have a mongoid session configured for whatever reason in a given environment, OkComputer will croak during intialization for that environment. This behavior was introduced sometime around v1.3.0 I believe. This PR prevents that.
=> Catch mongoid initialization errors

lib/ok_computer/built_in_checks/redis_check.rb, lib/okcomputer.rb, spec/ok_computer/built_in_checks/redis_check_spec.rb
Implements a built-in Redis health check. This works by calling the Redis INFO command. The initializer accepts any configuration hash that Redis.new accepts.
=> Redis health check

lib/okcomputer.rb
Engine depends on `configuration.rb` (e.g. in the after_initialize hook, `mount_at` is called),
thus configuration must be required (by some means) before the after_initialize block is executed.
When using `gem okcomputer` and `Bundler.require`, this works since all the files will be required
before the `after_initialize` block is executed. However, if not using `Bundler.require` (e.g. with
a Gemfile containing `gem okcomputer, require: false` or a gemspec containing
`s.add_dependency 'ok_computer'`) then the `after_initialize` hook can be called before
configuration.rb has been required (e.g. the hook's block is executed immediately if initialization has
already finished).
=> Require configuration before engine

lib/ok_computer/built_in_checks/sidekiq_latency_check.rb
According to https://github.com/mperham/sidekiq/blob/master/3.0-Upgrade.md
It is needed to require `sidekiq/api` since Sidekiq 3.0.
=> Added support for Sidekiq 4

config/routes.rb
This is a pretty straightforward change, it shouldn't need much explanation!
That said, I specifically needed it so I can build health checks programatically (I create AWS Elastic Load Balancers using aws-sdk-ruby).
It works:
```ruby
[9] pry(main)> OkComputer::Engine.routes.url_helpers.okcomputer_checks_path
=> "/my_health_checks/all"
[10] pry(main)> OkComputer::Engine.routes.url_helpers.okcomputer_check_path check: 'sdf'
=> "/my_health_checks/sdf"
```
`my_health_checks` being a random name I assigned to `OkComputer.mount_at`.
=> Give routes :as names so they can be referenced programatically

lib/ok_computer/configuration.rb, lib/okcomputer.rb
This is the follow up to this discussion: https://github.com/sportngin/okcomputer/pull/83. This should be all the changes required to make this work with my new `okcomputer-grape` gem. I'm going to close the original PR in favor of this one. Let me know if you see any issues with this approach.
=> Changes to make Rails not required

lib/ok_computer/built_in_checks/elasticsearch_check.rb, lib/ok_computer/built_in_checks/http_check.rb, lib/ok_computer/built_in_checks/solr_check.rb, spec/ok_computer/built_in_checks/http_check_spec.rb
Ran into an issue where I needed to support http basic auth in checks for Elasticsearch. It appears that the current http check doesn't support that, so this change should take care of it.
=> Adding support for http basic auth in http checks

.travis.yml, lib/ok_computer/built_in_checks/http_check.rb, spec/ok_computer/built_in_checks/http_check_spec.rb
As stupid as it sounds, some services will attempt to authenticate an unprotected route when an Authorization header is set.
=> Only set Authorization header when basic auth is required

lib/ok_computer/registry.rb, spec/controllers/ok_computer_controller_spec.rb
Closes https://github.com/sportngin/okcomputer/issues/94.
This is a user-supplied value, so should be either sanitized or not rendered. Not rendering it feels simplest. While attack vector is small (since presumably only the attacker will see this response), it's simple enough to close that we might as well.
/okcomputer/asdf.txt
```text
No check registered with 'asdf'
```
/okcomputer/asdf.json
```json
{"error":"No check registered with 'asdf'"}
```
/okcomputer/asdf.txt
```text
No matching check 
```
/okcomputer/asdf.json
```json
{"error":"No matching check"}
```
=> Stop rendering name of requested check

lib/ok_computer/built_in_checks/cache_check.rb, spec/ok_computer/built_in_checks/cache_check_spec.rb
The default `FileCacheStore` doesn't have a `#stats` method.
=> Support Rails cache configurations that don't report statistics

config/locales/okcomputer.en.yml, lib/ok_computer/check.rb
We'd like to change the okcomputer status to be a little more scannable, e.g.:
```
OK      : ruby - Ruby 2.3.1-p112
FAILED  : version - Unable to determine version
```
Here, I push that output into an i18n file that can be easily overridden in the host application.
=> Use i18n strings for check messages

config/locales/okcomputer.en.yml, lib/ok_computer/check.rb, spec/ok_computer/check_spec.rb
E.g.:
```
default: PASSED Application is running (0ms)
database: PASSED Schema version: 20160818140248 (1ms)
```
=> Benchmark and report the time Check#check takes to execute

lib/ok_computer/legacy_rails_controller_support.rb
Closes https://github.com/sportngin/okcomputer/issues/120.
While we don't officially support it, this syntax will work on both Ruby 1.9 and Ruby 2.x, so we might as well.
=> Be nicer to Ruby 1.9

lib/ok_computer/built_in_checks/generic_cache_check.rb, spec/ok_computer/built_in_checks/generic_cache_check_spec.rb
Before: 
```
generic_cache_check: {
message: "Able to read and write",
success: true,
time: 0.00024213300002884353
},
```
After:
```
generic_cache_check: {
message: "Able to read and write via Memory store",
success: true,
time: 0.00024213300002884353
},
```
=> Add cache_store name to generic cache check message

lib/ok_computer/check.rb, spec/ok_computer/registry_spec.rb
Closes https://github.com/sportngin/okcomputer/pull/129. This is an alternate implementation to https://github.com/sportngin/okcomputer/pull/130, which felt like it began to sprawl a bit as a fix. Instead of coercing symbols to strings on the way in (and massaging methods which interact with check names to continue to work as expected), this performs the coercion only when sorting checks, which is where the exception triggered.
=> Accept mix of strings and symbols as check names

lib/ok_computer/built_in_checks/sequel_check.rb, lib/okcomputer.rb, okcomputer.gemspec, spec/ok_computer/built_in_checks/sequel_check_spec.rb
* Created SequelCheck file
* Allows for overwriting of the migration directory as well as providing
a different database to check against.
* Modify the main okcomputer.rb load file to check for ActiveRecord and Sequel.
Logic here is if it's automatically adding a check for one ORM, it should add
it for the other. 
I now wrapped the ActiveRecord check around `defined?(ActiveRecord)`. I don't think this should be a breaking change because the gem actually checks for `defined?(Rails)` just slightly above it, which usually means they passed the initial rails boot process of the app.
addresses #135
=> Add SequelCheck

README.markdown, lib/ok_computer/check.rb, lib/ok_computer/configuration.rb, spec/ok_computer/check_spec.rb, spec/ok_computer/configuration_spec.rb
Currently when a check is executed, unless the client that is invoking the check logs the results, it's not possible to know what the result was. This mitigates that issue by allowing `OkComputer.logger` to be set to a logger that will log the text when a check is performed. Note that by default the logger is set to `Logger.new nil`, which performs a no-op when called, so the current behavior remains unchanged.
```ruby
OkComputer.logger = Rails.logger
```
```sh
[okcomputer] mycheck: PASSED mymessage (0s)
```
=> Add the ability to log check text

.travis.yml, lib/ok_computer/built_in_checks/active_record_migrations_check.rb, spec/ok_computer/built_in_checks/active_record_migrations_check_spec.rb
- Makes `OkComputer::ActiveRecordMigrationsCheck` compatible with Rails 5.2
- Also updated the travis build matrix for supported versions of Ruby and Rails
- Kept Rails 3.2 in the build matrix for posterity (no reason to drop that yet)
- Fixes #146
=> Make ActiveRecordMigrationsCheck compatible with Rails 5.2

lib/ok_computer/built_in_checks/solr_check.rb, spec/ok_computer/built_in_checks/solr_check_spec.rb
Solr 7 defaults to a JSON response format, instead of the expected XML response. The HTTP status code should also reflect the current status value, so I wonder if it might be better to drop the content check entirely.
=> Update the built-in SolrCheck for compatibility with Solr 7+

lib/ok_computer/check.rb, spec/ok_computer/check_spec.rb
Previously, the time would return seconds as integer values. This update returns milliseconds, too.
```ruby
time = 3.141
sprintf('%0.000f', time)
sprintf('%.3f', time)
```
=> Update time format to return fractional seconds

app/controllers/ok_computer/ok_computer_controller.rb
This commit in [Rack 2.1](https://github.com/rack/rack/commit/e6bdee4c16310e078093c0282f2f5449fdd130cd) has it validating status code symbols instead of defaulting to a 500 error on any unknown status.
=> Update status code handling for compatibility with Rack 2.1

.travis.yml
This adds ruby 2.7 to the TravisCI tests
=> Add Ruby 2.7 to tests

lib/ok_computer/built_in_checks/neo4j_check.rb, spec/ok_computer/built_in_checks/neo4j_check_spec.rb
This solves #163 by rescuing from the correct faraday error.
=> Rescue from correct Faraday error

.travis.yml
`"~> 5.1"` and `"~> 5.2"` would resolve to the same version, and `"~> 6.0"` resolves to 6.1.x
References #169
=> Correct the rails versions in the travis build matrix

lib/ok_computer/built_in_checks/app_version_check.rb, spec/ok_computer/built_in_checks/app_version_check_spec.rb
- Adds ability to customize AppVersionCheck with optional `file`, `env`, and `transform` arguments.
- Closes #167
=> Add ability to customize AppVersionCheck 

README.markdown
It works fine in Rails 7.0. 
Although we'd need to close this one first: https://github.com/sportngin/okcomputer/pull/174
=> Add Rails 7.0 support in the README.md

lib/ok_computer/built_in_checks/generic_cache_check.rb
- Fixes minor typo in the cache_key of `GenericCacheCheck#cache_key`
=> Update cache_key in GenericCacheCheck
